repos:

  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
      -   id: check-yaml
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
      -   id: check-added-large-files
      -   id: debug-statements
          language_version: python3

  -   repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
      -   id: black
          args: [--safe]

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.910
      hooks:
      -   id: mypy
          files: .
          args: [--strict, --ignore-missing-imports]

  -   repo: local
      hooks:
      -   id: pylint
          name: pylint
          files: .
          entry: pylint
          language: system
          types: [python3]
          args: [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=.pylintrc", # Link to your config file
          ]
